name: CI
on: push
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run linter
        run: |
          yarn typescript
          yarn lint
      - name: Run tests
        run: yarn testcoverage

